name: Build
on:
    push:
        branches: [main]

jobs:
    build-and-lint:
        runs-on: ubuntu-latest
        steps:
            # Checkout project repository
            - name: Checkout
              uses: actions/checkout@v2.3.4

            # Setup Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  registry-url: https://registry.npmjs.org/
                  node-version: '16'

            # Install dependencies (required by Run tests step)
            - name: Install dependencies
              run: npm ci

            # Tests
            #- name: Run tests
            #  run: yarn test

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
