name: 'Create release'

on:
    push:
        tags:
            - 'v*'

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm ci
            - name: Build bundle
              run: npm run build
            - name: Create release file
              run: echo ${{ github.sha }} > Release.txt
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: 'Release.txt'
                  generateReleaseNotes: true
                  token: ${{ secrets.GITHUB_TOKEN }}
